### ISSUE TITLE
Enable saving ouput netcdf file by default

### ISSUE THREAD

**Issue by zxdawn** [eamarais/erc-uptrop#10]
Although it prints out the saving info, the saving line is commented:
https://github.com/eamarais/erc-uptrop/blob/388a56139e92ee7d88e7f77830f7851acf799de4/uptrop/cloud_slice_tropomi_no2.py#L931

**Comment by eamarais** [comment]
Hi @zxdawn, I've very recently updated the code for this and have a prerelease (v2.0.0) that you're welcome to use instead. This includes the ability to use the new reprocessed TROPOMI data product.

**Comment by zxdawn** [comment]
@eamarais Thanks for the updates. I'm also using the PAL data for my lightning NOx research. The v2.0.0 release works well.

I have two questions, could you please take a look when you're free?

1. Is it suitable to set the pmin=cp_min (the lowest cloud in my convective cloud mask)  and pmax=p_tropo for each case? and split it into several sub-plevels to get NO2 profile above one cloud?

2. Because the comparison between Pandora and TROPOMI is performed over the three tropic stations (mentioned in your AMT paper), is it necessary to correct the stratospheric column for mid-latitude and high-latitude regions? Maybe, that's different in different latitudes. Besides, the [spatial heterogeneity](https://doi.org/10.5194/amt-15-41-2022) could also affect the comparison results.
