### ISSUE TITLE
Using relative image path for `out_plot_file_path`

### ISSUE THREAD

**Issue by zxdawn** [eamarais/erc-uptrop#8]
https://github.com/eamarais/erc-uptrop/blob/388a56139e92ee7d88e7f77830f7851acf799de4/uptrop/cloud_slice_tropomi_no2.py#L928

It should be `out_plot_file_path = path.join(args.out_dir, 'Images/', out_plot_file)`. Otherwise, the joined path will be  `/Images/tropomi****`.

**Comment by eamarais** [comment]
This is updated in the latest code version that I've recently uploaded to the git repo.
